// ================================================
// CSS Gradient Writer
// Exports gradients as CSS linear-gradient() values
// ================================================

/**
 * Build a CSS text file with all gradients as CSS custom properties
 * and class definitions.
 */
function buildCssGradients(paletteData) {
    var palettes = paletteData.Palettes;
    var lines = [];

    lines.push('/* ' + paletteData.Name + ' */');
    lines.push('/* Generated by Gradient Converter */');
    lines.push('/* ' + palettes.length + ' gradient' + (palettes.length !== 1 ? 's' : '') + ' */');
    lines.push('');

    // CSS custom properties
    lines.push(':root {');
    for (var i = 0; i < palettes.length; i++) {
        var safeName = palettes[i].Name.replace(/[^a-zA-Z0-9_-]/g, '-').replace(/--+/g, '-').toLowerCase();
        lines.push('  --gradient-' + safeName + ': ' + buildCssGradientValue(palettes[i].Colours) + ';');
    }
    lines.push('}');
    lines.push('');

    // Utility classes
    for (var i = 0; i < palettes.length; i++) {
        var safeName = palettes[i].Name.replace(/[^a-zA-Z0-9_-]/g, '-').replace(/--+/g, '-').toLowerCase();
        lines.push('.gradient-' + safeName + ' {');
        lines.push('  background: ' + buildCssGradientValue(palettes[i].Colours) + ';');
        lines.push('}');
        lines.push('');
    }

    return lines.join('\n');
}

/**
 * Build a single CSS linear-gradient() value from colour stops.
 */
function buildCssGradientValue(colours) {
    var stops = [];

    for (var i = 0; i < colours.length; i++) {
        var c = colours[i];
        var r = Math.round(c.Red * 255);
        var g = Math.round(c.Green * 255);
        var b = Math.round(c.Blue * 255);
        var a = c.Alpha !== undefined ? c.Alpha : 1;
        var pos = (c.Position * 100).toFixed(1) + '%';

        if (a < 1) {
            stops.push('rgba(' + r + ', ' + g + ', ' + b + ', ' + a.toFixed(3) + ') ' + pos);
        } else {
            stops.push('rgb(' + r + ', ' + g + ', ' + b + ') ' + pos);
        }
    }

    return 'linear-gradient(90deg, ' + stops.join(', ') + ')';
}

/**
 * Download gradients as a CSS file.
 */
function writeCssGradient(paletteData) {
    var text = buildCssGradients(paletteData);
    var blob = new Blob([text], { type: "text/css" });
    var safeName = paletteData.Name.replace(/[<>:"\/\\|?*]/g, '_');
    saveFile(blob, safeName + ".css");
}
